Fix error in CI
https://github.com/9sako6/zoi/actions/runs/3384125364/jobs/5620729313

```
 gem install zoi -v 0.1.6
  zoi version
  shell: /bin/bash -e {0}
  env:
    PATH: /usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.9.1/x64
Successfully installed thor-1.2.1
Successfully installed zoi-0.1.6
2 gems installed
/Users/runner/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/zoi-0.1.6/exe/zoi:6:in `<top (required)>': undefined method `chomp' for nil:NilClass (NoMethodError)

args = File.pipe?($stdin) ? ARGV + $stdin.gets.chomp.split : ARGV
                                              ^^^^^^
	from /Users/runner/hostedtoolcache/Ruby/3.1.2/x64/bin/zoi:25:in `load'
	from /Users/runner/hostedtoolcache/Ruby/3.1.2/x64/bin/zoi:25:in `<main>'
```